#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

// Init application.
$application = new Symfony\Component\Console\Application('Backup CLI', '@package_version@');

// Add commands.
$application->addCommands(
  [
    new BackupCli\Commands\ProfileNewDb,
    new BackupCli\Commands\ProfileListDb,
    new BackupCli\Commands\BackupDb,
    new BackupCli\Commands\BackupFiles,
    new BackupCli\Commands\RestoreDb,
    new BackupCli\Commands\RestoreFiles,
    new BackupCli\Commands\SelfUpdate,
  ]
);

// Run the app.
$application->run();
